# Data-based DJ Sets {#data-4-DJs}

#### Keywords {-}

Dynamic playlist generation, DJ set, mashup, concert, neural network

## "I love technology. We can be our own DJs wherever we go." -Ludacris

Do you ever find yourself changing radio stations during the outro of a song? Or skipping ahead to your favorite part of a song on Spotify? Or maybe you like to hear songs in their entirety, but that darn DJ keeps jumping around and killing your vibe. Have you mastered the art of designing a good playlist when you get handed the smart phone in a car full of your friends?

Now to any DJs: You are tasked with not only selecting songs your audience wants, but ordering them properly and transitioning between them. When do you mix songs for a seamless transition and when do you pause the music to yell to your fans that their city has been the wildest one on the entire tour? You probably know that if you play all your chart-toppers at the beginning of a show, the audience will get bored at the end, but could you both open and close your set with that monster hit from your first album and get a positive response both times?

For the casual music enthusiast and Avicii alike, the art of the perfect playlist is an elusive goal. Creativity can't be fully automated, but that's that doesn't mean we can't let data help direct the creative process.

## "A DJ can't just play one song. It's about playing a set, or how you connect songs in those two hours, and where you place them." -Zedd

Introducing Data-4-DJs: a service that helps casual or professional DJs optimally mix songs. Data is collected from multiple sources including industry partners Spotify, Apple Music, and Pandora to identify patterns in listeners' preferences. Data is recorded on what songs users tend to accompany with one another, what order songs are played in, and when songs are skipped or replayed. The broad user base as well as multi-genre platforms allow for a massive and representative collection of data.

From this raw data, trends are identified both for the general population and specific listeners. Songs might be compatible for a number of reasons, for example similar genre, beats per minute, or lyrical content. These features and more are represented in an neural network, so the derived relationships and optimal policy can be generalized to any new set of songs. These general principles are then refined for specific listeners. If a DJ knows his or her audience (at a wedding for example) or more broadly the audience demographic (at a concert), these more tailored details can be exploited. Preliminary efforts, such as that by Pampalk, Pohle, & Widmer have demonstrated success using primarily genre and artist information [@ other citekey]. Using heuristics such as n nearest neighbors to a seed song, they were able to significantly reduce the number of songs a user would skip when compared to a shuffled playlist. This could work for certain scenarios but within a specific artist's catalogue, it would be insufficient. Generalizing with other song attributes in a manner similar to Pandora's Music Genome Project, which uses over 450 musical attributes to categorize songs fundamentally, will allow for better selection within an artist's repertoire [@ MGP citekey].

Within a song, our algorithm utilizes unsupervised learning to identify sections such as an intro, verse, chorus, or bridge, as well as more subtle musical features such as instrumentation, timbre, or texture. By observing user actions, our software determines a policy to predictively mix songs in a way that appeals to these users. This is what truly sets us apart from simpler algorithms based solely on genre or artist.

Our service also allows direct user feedback. An artist can integrate Data-4-DJs with their website and collect users responses to a show they attended. It collects both quantitative and qualitative feedback so that direct a direct comparison can be made numerically between two shows or more nuanced feedback can be used to fine-tune those hard to quantify elements. To acquire more representative feedback, we partner with ticket distributers to automatically email all attendees soliciting feedback. To correct for the response bias, we process the data for our customer, over-representing late responses which are more representative of the population of attendees than early responses.

Another advantage for the casual user is the "set it and forget it" option. Rather than selecting songs one-by-one for a playlist, a single song can be used as a seed and the algorithm can take over from there. This may sound similar to Pandora's radio service, but it improves upon it by using a combination of song attributes and metadata, and sources from multiple industry partners who attract different demographics. More importantly, the goal is different: Pandora is a music discovery service, whereas our service is about creating an experience [@ Wikipedia citekey]. Thus, they fall on different ends of the exploration vs exploitation spectrum.

## "When you go see a good DJ, you’ll know it... Between the guy who’s phoning it in and the guy who’s obsessively working it to give you the best show of his life." -Kaskade

This service doesn't replace artistic creativity; it is complementary. We know that the best artists succeed because they can channel emotion in unexplainable ways. But we also know that every artist has their hits and misses, and we want to use data to help them reach their maximum potential.

Whether at a rave, a wedding, or jamming with your friends, Data-4-DJs allows you to provide the optimal listening experience as backed by research, data, and your listeners' own preferences. We know there is nothing more important to you than giving your listeners the best experience possible and we want to help you in that mission.
